import { ClerkProvider } from "@clerk/nextjs";
import "@/styles/globals.css";
import { fontSans } from "@/lib/fonts";
import { cn } from "@/lib/utils";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body
          className={cn(
            "relative flex min-h-screen w-full flex-col justify-center scroll-smooth bg-background font-sans antialiased",
            fontSans.variable
          )}
        >
          <main>{children}</main>
        </body>
      </ClerkProvider>
    </html>
  );
}
